# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nightsky_pb2 as nightsky__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in nightsky_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NightSkyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVisibility = channel.unary_unary(
                '/NightSkyService/GetVisibility',
                request_serializer=nightsky__pb2.VisibilityRequest.SerializeToString,
                response_deserializer=nightsky__pb2.VisibilityResponse.FromString,
                _registered_method=True)
        self.GetNightEvent = channel.unary_unary(
                '/NightSkyService/GetNightEvent',
                request_serializer=nightsky__pb2.NightEventRequest.SerializeToString,
                response_deserializer=nightsky__pb2.NightEventResponse.FromString,
                _registered_method=True)
        self.SaveCamera = channel.unary_unary(
                '/NightSkyService/SaveCamera',
                request_serializer=nightsky__pb2.SaveCameraRequest.SerializeToString,
                response_deserializer=nightsky__pb2.SaveCameraResponse.FromString,
                _registered_method=True)
        self.GetUpcomingNightEventsStream = channel.unary_stream(
                '/NightSkyService/GetUpcomingNightEventsStream',
                request_serializer=nightsky__pb2.UpcomingNightEventsRequest.SerializeToString,
                response_deserializer=nightsky__pb2.UpcomingNightEventsResponse.FromString,
                _registered_method=True)


class NightSkyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetVisibility(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNightEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCamera(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUpcomingNightEventsStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NightSkyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVisibility': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVisibility,
                    request_deserializer=nightsky__pb2.VisibilityRequest.FromString,
                    response_serializer=nightsky__pb2.VisibilityResponse.SerializeToString,
            ),
            'GetNightEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNightEvent,
                    request_deserializer=nightsky__pb2.NightEventRequest.FromString,
                    response_serializer=nightsky__pb2.NightEventResponse.SerializeToString,
            ),
            'SaveCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCamera,
                    request_deserializer=nightsky__pb2.SaveCameraRequest.FromString,
                    response_serializer=nightsky__pb2.SaveCameraResponse.SerializeToString,
            ),
            'GetUpcomingNightEventsStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetUpcomingNightEventsStream,
                    request_deserializer=nightsky__pb2.UpcomingNightEventsRequest.FromString,
                    response_serializer=nightsky__pb2.UpcomingNightEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NightSkyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('NightSkyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NightSkyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetVisibility(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/NightSkyService/GetVisibility',
            nightsky__pb2.VisibilityRequest.SerializeToString,
            nightsky__pb2.VisibilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNightEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/NightSkyService/GetNightEvent',
            nightsky__pb2.NightEventRequest.SerializeToString,
            nightsky__pb2.NightEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/NightSkyService/SaveCamera',
            nightsky__pb2.SaveCameraRequest.SerializeToString,
            nightsky__pb2.SaveCameraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUpcomingNightEventsStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/NightSkyService/GetUpcomingNightEventsStream',
            nightsky__pb2.UpcomingNightEventsRequest.SerializeToString,
            nightsky__pb2.UpcomingNightEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
