# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nightsky.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'nightsky.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enightsky.proto\"%\n\x11VisibilityRequest\x12\x10\n\x08location\x18\x01 \x01(\t\"#\n\x12VisibilityResponse\x12\r\n\x05level\x18\x01 \x01(\t\"\x13\n\x11NightEventRequest\"4\n\x12NightEventResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t\"3\n\x11SaveCameraRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t\"4\n\x12SaveCameraResponse\x12\r\n\x05model\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t\",\n\x1aUpcomingNightEventsRequest\x12\x0e\n\x06period\x18\x01 \x01(\t\":\n\x1bUpcomingNightEventsResponse\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\r\n\x05\x65vent\x18\x02 \x01(\t2\x99\x02\n\x0fNightSkyService\x12\x38\n\rGetVisibility\x12\x12.VisibilityRequest\x1a\x13.VisibilityResponse\x12\x38\n\rGetNightEvent\x12\x12.NightEventRequest\x1a\x13.NightEventResponse\x12\x35\n\nSaveCamera\x12\x12.SaveCameraRequest\x1a\x13.SaveCameraResponse\x12[\n\x1cGetUpcomingNightEventsStream\x12\x1b.UpcomingNightEventsRequest\x1a\x1c.UpcomingNightEventsResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nightsky_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VISIBILITYREQUEST']._serialized_start=18
  _globals['_VISIBILITYREQUEST']._serialized_end=55
  _globals['_VISIBILITYRESPONSE']._serialized_start=57
  _globals['_VISIBILITYRESPONSE']._serialized_end=92
  _globals['_NIGHTEVENTREQUEST']._serialized_start=94
  _globals['_NIGHTEVENTREQUEST']._serialized_end=113
  _globals['_NIGHTEVENTRESPONSE']._serialized_start=115
  _globals['_NIGHTEVENTRESPONSE']._serialized_end=167
  _globals['_SAVECAMERAREQUEST']._serialized_start=169
  _globals['_SAVECAMERAREQUEST']._serialized_end=220
  _globals['_SAVECAMERARESPONSE']._serialized_start=222
  _globals['_SAVECAMERARESPONSE']._serialized_end=274
  _globals['_UPCOMINGNIGHTEVENTSREQUEST']._serialized_start=276
  _globals['_UPCOMINGNIGHTEVENTSREQUEST']._serialized_end=320
  _globals['_UPCOMINGNIGHTEVENTSRESPONSE']._serialized_start=322
  _globals['_UPCOMINGNIGHTEVENTSRESPONSE']._serialized_end=380
  _globals['_NIGHTSKYSERVICE']._serialized_start=383
  _globals['_NIGHTSKYSERVICE']._serialized_end=664
# @@protoc_insertion_point(module_scope)
